### ISSUE TITLE
PHP 8.1 Deprecated function rtrim() Passing null to parameter #1 ($string) of type string is deprecated in backdrop_basename()

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/svg_image#1]
**Steps to reproduce**

1. Start with PHP 8.1 site
2. Add and enable module svg_image
3. Add image field to content type
4. Upload image
5. Set display type to Image (SVG support)
6. View page

**Actual result**
Image uploads but get error:
> Deprecated function: rtrim(): Passing null to parameter #1 ($string) of type string is deprecated in backdrop_basename() (line 2552 of /app/docroot/core/includes/file.inc).

Also get this on viewing content if field supports svg display but doesn't contain svg.

Using the HEAD version of the `devel` module (released version hangs with Krumo) and using Krumo Backtrace I was able to trace this back:
```
krumo($object); (Array, 37 elements)
36: rtrim() (Array, 1 element)
35: backdrop_basename() (Array, 2 elements)
34: BackdropLocalStreamWrapper::getMimeType() (Array, 2 elements)
33: file_get_mimetype() (Array, 2 elements)
32: svg_image_is_svg() (Array, 2 elements)
31: svg_image_preprocess_image_style() (Array, 2 elements)
30: theme() (Array, 2 elements)
```
Then a further debug finds that this is empty when the error happens:
https://github.com/backdrop-contrib/svg_image/blob/4c3d33a22cd85256959f3a13ed9cc241a353d085/svg_image.module#L18

**Expected result**
No errors

---

[PR ](https://github.com/backdrop-contrib/svg_image/pull/2) added

**Comment by yorkshire-pudding** [comment]
@herbdool - I've just noticed that you're not in the watchers list for this project so won't have been notified that there is an issue with a fix in a PR.  (see also #3)

**Comment by herbdool** [comment]
Thanks @yorkshire-pudding. Feel free to "at" me to get my attention. Usual info-overload problem.
